variable "ad_app_name" {}
variable "ad_app_home_page" {}
variable "ad_app_reply_urls" {}
variable "available_to_other_tenants" {}
variable "oauth2_allow_implicit_flow" {}
variable "ad_app_type" {}
variable "service_principal_pwd" {}
variable "service_principal_end_date" {}
variable "cluster_name" {}
variable "location" {}
variable "resource_group_name" {}
variable "aks_dns_prefix" {}
variable "aks_node_size" {}
variable "aks_node_user_name" {}
variable "aks_node_pool_name" {}
variable "aks_node_count" {}
variable "enable_aks_auto_scale" {}
variable "node_max_count" {}
variable "node_min_count" {}
variable "aks_rbac" {}
variable "kubernetes_verrsion" {}
variable "ssh_public_key" {}